;	PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l412kb]
platform = ststm32
board = nucleo_l412kb
monitor_speed = 115200
framework = arduino
build_flags = 
	-D BB_MARTHA
lib_deps = 
	adafruit/Adafruit LIS2MDL@^2.1.8
	adafruit/Adafruit LSM6DS@^4.7.2
	adafruit/Adafruit SPIFlash@^5.0.1

[env:martha_stm]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
test_framework = unity
lib_ldf_mode = deep
monitor_speed = 115200
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D PCB_MARTHA
lib_deps = 
	adafruit/Adafruit LIS2MDL@^2.1.8
	adafruit/Adafruit LSM6DS@^4.7.2
	adafruit/Adafruit SPIFlash@^5.0.1
debug_tool = stlink
upload_protocol = stlink
upload_port =

[env:martha_stm_usb_as_radio]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
test_framework = unity
lib_ldf_mode = deep
monitor_speed = 115200
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D PCB_MARTHA
	-D USB_RADIO
lib_deps = 
	adafruit/Adafruit LIS2MDL@^2.1.8
	adafruit/Adafruit LSM6DS@^4.7.2
	adafruit/Adafruit SPIFlash@^5.0.1
debug_tool = stlink
upload_protocol = stlink
upload_port =

[env:martha_stm_sim]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
test_framework = unity
lib_ldf_mode = deep
monitor_speed = 115200
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D PCB_MARTHA
	-D SIM
	-O0
lib_deps = 
	adafruit/Adafruit LIS2MDL@^2.1.8
	adafruit/Adafruit LSM6DS@^4.7.2
	Wire
	SPI
	adafruit/Adafruit SPIFlash@^5.0.1
debug_tool = stlink
upload_protocol = stlink
upload_port =
